
package com.rightnow.ws.wsdl.v1;

import javax.xml.ws.WebFault;
import com.rightnow.ws.faults.v1.RequestErrorFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RequestErrorFault", targetNamespace = "urn:faults.ws.rightnow.com/v1")
public class RequestErrorFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RequestErrorFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public RequestErrorFault(String message, RequestErrorFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public RequestErrorFault(String message, RequestErrorFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.rightnow.ws.faults.v1.RequestErrorFaultType
     */
    public RequestErrorFaultType getFaultInfo() {
        return faultInfo;
    }

}
