
package com.rightnow.ws.wsdl.v1;

import javax.xml.ws.WebFault;
import com.rightnow.ws.faults.v1.ServerErrorFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ServerErrorFault", targetNamespace = "urn:faults.ws.rightnow.com/v1")
public class ServerErrorFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServerErrorFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ServerErrorFault(String message, ServerErrorFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ServerErrorFault(String message, ServerErrorFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.rightnow.ws.faults.v1.ServerErrorFaultType
     */
    public ServerErrorFaultType getFaultInfo() {
        return faultInfo;
    }

}
