
package com.rightnow.ws.wsdl.v1_2;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RightNowSyncService", targetNamespace = "urn:wsdl.ws.rightnow.com/v1_2", wsdlLocation = "http://ubankhelp--tst.custhelp.com/cgi-bin/ubankhelp--tst.cfg/services/soap?wsdl=typed")
public class RightNowSyncService
    extends Service
{

    private final static URL RIGHTNOWSYNCSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.rightnow.ws.wsdl.v1_2.RightNowSyncService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.rightnow.ws.wsdl.v1_2.RightNowSyncService.class.getResource(".");
            url = new URL(baseUrl, "http://ubankhelp--tst.custhelp.com/cgi-bin/ubankhelp--tst.cfg/services/soap?wsdl=typed");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://ubankhelp--tst.custhelp.com/cgi-bin/ubankhelp--tst.cfg/services/soap?wsdl=typed', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RIGHTNOWSYNCSERVICE_WSDL_LOCATION = url;
    }

    public RightNowSyncService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RightNowSyncService() {
        super(RIGHTNOWSYNCSERVICE_WSDL_LOCATION, new QName("urn:wsdl.ws.rightnow.com/v1_2", "RightNowSyncService"));
    }

    /**
     * 
     * @return
     *     returns RightNowSyncPort
     */
    @WebEndpoint(name = "RightNowSyncPort")
    public RightNowSyncPort getRightNowSyncPort() {
        return super.getPort(new QName("urn:wsdl.ws.rightnow.com/v1_2", "RightNowSyncPort"), RightNowSyncPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RightNowSyncPort
     */
    @WebEndpoint(name = "RightNowSyncPort")
    public RightNowSyncPort getRightNowSyncPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:wsdl.ws.rightnow.com/v1_2", "RightNowSyncPort"), RightNowSyncPort.class, features);
    }

}
