
package com.rightnow.ws.wsdl.v1_2;

import javax.xml.ws.WebFault;
import com.rightnow.ws.faults.v1_2.ServerErrorFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ServerErrorFault", targetNamespace = "urn:faults.ws.rightnow.com/v1_2")
public class ServerErrorFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServerErrorFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ServerErrorFault(String message, ServerErrorFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ServerErrorFault(String message, ServerErrorFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.rightnow.ws.faults.v1_2.ServerErrorFaultType
     */
    public ServerErrorFaultType getFaultInfo() {
        return faultInfo;
    }

}
