
package com.rightnow.ws.wsdl.v1_2;

import javax.xml.ws.WebFault;
import com.rightnow.ws.faults.v1_2.UnexpectedErrorFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "UnexpectedErrorFault", targetNamespace = "urn:faults.ws.rightnow.com/v1_2")
public class UnexpectedErrorFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnexpectedErrorFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public UnexpectedErrorFault(String message, UnexpectedErrorFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public UnexpectedErrorFault(String message, UnexpectedErrorFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.rightnow.ws.faults.v1_2.UnexpectedErrorFaultType
     */
    public UnexpectedErrorFaultType getFaultInfo() {
        return faultInfo;
    }

}
